### ISSUE TITLE
MorphModel seeder help.

### ISSUE THREAD

**Issue by kikoseijo** [kevupton/ethereal#1]
Hello Sr,

Playing with this Wonderfull library but I bump in to an issue trying to make seeders-

got this:

```php
$factory->define(App\Models\Post::class, function ($faker) {
    $taggable = [
        App\Models\PostVideo::class,
        App\Models\PostAudio::class,
    ];
    return [
        'title' => $faker->catchPhrase,
        'post_id'   => 1,
        'post_type' => $faker->randomElement($taggable),
    ];
});

$factory->defineAs(App\Models\Post::class, 'audio', function (Faker\Generator $faker) use ($factory) {
    $follow = $factory->raw(App\Models\Post::class);
    $extras = [
        'post_id'   => $faker->randomElement(App\Models\PostAudio::pluck('id')->toArray()),
        'post_type' => App\Models\PostAudio::class,
    ];
    return array_merge($follow, $extras);
});
```

I run the seeds doing this:

```php
factory(App\Models\Post::class, 'soundcloud', rand(1,8))->create([
              'hub_id' => $hub->id
            ]);
            factory(App\Models\Post::class, 'youtube', rand(1,8))->create([
              'hub_id' => $hub->id
            ]);
```

main class

```php
    // relationships
    public static $relationsData = [
        'post' => [self::MORPH_TO],
    ];
```

Subclass

```php
    protected $morphBy = 'post';
    protected $morphTable = 'posts'; //the name of the parent table
    protected $morphModel = Post::class; //the class of the parent table
```

Its complaining about declaring the `$relationsData` in the subclass.

```
Symfony\Component\Debug\Exception\FatalThrowableError: Access to undeclared static property: App\Models\PostVideo::$relationsData in /Kevupton/Ethereal/Models/MorphModel.php:23
```

Any idea why? Need more info?
Thank you, excellent job btw.

**Comment by kikoseijo** [comment]
I guess with your Ethereal class I don't have to do such a complex relations, I just need to define each one individually.

Thanks anyway!

**Comment by kikoseijo** [comment]
Naa, can't make it work, seems that here `$class::$relationsData[$this->morph_name] = array(self::MORPH_ONE, $this->morphModel, $this->morphBy);` you calling the subclass and per your instructions this is declared in the parent class, not the children.

If you could look at it, ..    😇

**Comment by kikoseijo** [comment]
I have done some debug, got it working by declaring and empty

```php
public static $relationsData = [];
```

I Seen you try to setup but does not exist. 

Factories seeder can't make it work. I should investigate factories, and probably them not linked to the models and them using query builder instead of eloquent.

**Comment by kikoseijo** [comment]
Finally!

```php
Model::unguard();
```

I tries to save all data in the child, don't know why!...

**Comment by kevupton** [comment]
Haha oh sorry didnt see this notification. Glad you managed to figure it out!  😄 

I think my docs can be a bit confusing and this code at the time was quite messy, so I decided to do a major clean / revamp of this entire library. haha, almost everything is different. (in a good way 😛)

All the new functionality is in the new version `2.4`.

I also broke everything down into pieces, so if you dont want to use all the functionality you can just use some through the traits (just adding them to your base model).

I think the new [MorphModel](https://github.com/kevupton/ethereal/wiki/MorphModel) is a fair bit simpler and nicer.
