### ISSUE TITLE
Laravel-json-response

### ISSUE THREAD

**Issue by kikoseijo** [kevupton/ethereal#3]
There is conflict here

```
   - kevupton/ethereal v2.4 requires kevupton/laravel-json-response dev-master -> satisfiable by kevupton/laravel-json-response[dev-master]but these conflict with your requirements or minimum-stability.
```

Will avoid updating.

**Comment by kevupton** [comment]
Oh woops. I just fixed that dependency. it should work now.

**Comment by kikoseijo** [comment]
You also removed the lumen_resource()
I was using it, you using something better?
Works well.

**Comment by kevupton** [comment]
Yeh I thought it was a bit too complex, and I could probably simplify the functionality.

So I decided to implement a static method `MyController::routes()`  with the docs [here](https://github.com/kevupton/ethereal/wiki/hasresourceinterface#define-the-route)

But basically now you can do this:
```php

$path = 'my/custom/path';
$namespace = 'Auth';
$actionOverrides = [];
\App\Http\Controllers\TestController::routes(['index', 'store'], $path, $actionOverrides, $namespace);

// or 

\App\Http\Controllers\TestController::routes(); // for all routes with path:
```

It auto makes the path based on the controller name. So for this test controller the path would be `test`. (snake cased, with removal on controller).

**Comment by kevupton** [comment]
maybe I should re-add the function but just make it deprecated. So it doesn't cause errors on upgrade, or at least write a change log.

**Comment by kevupton** [comment]
I added it back in in version `2.4.1` just made it depracated.
